baseURL = "https://aebou.rbind.io/"
title   = "Anicet Ebou"

DefaultContentLanguage = "en"

theme = "hugo-theme-hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

googleAnalytics = "UA-111109114-1"
disqusShortname = "aebou"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Anicet Ebou"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Metadata mostly used in document's head
  description = "Anicet Ebou's Website"
  keywords = "R blog, Bioinformatics blog, Personal blog"
  #images = [""]

  homeSubtitle = "Bioinformatics & Big Data"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = true  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  # contentTypeName = "blog"
  # Default theme "light" or "dark"
  defaultTheme = "light"
  themeColor = "#252627"

  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Set to a valid CSS color to change the cursor in the logo.
    logoColor    = "#63c5da"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/anicetebou"

  [[params.social]]
    name = "email"
    url  = "anicet.ebou@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/Ebedthan"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/anicet-ebou"

[languages]
  [languages.en]
    subtitle  = "Biology & Data"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.fr]
    subtitle  = "Biology & Data"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "talks"
    name       = "Talks"
    url        = "talks/"
  [[menu.main]]
    identifier = "tutorials"
    name       = "Tutorials"  
    url        = "tutorials/"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
